### Conclusions

Now that we've gone through the data, let's take a step back to interpret our results and look at the patterns that have emerged. 

For both legal immigration and refugee immigration, there were positive, linear associations between these variables and violent and property crime rates in the United States. For illegal immigration, there were negative, linear associations across all of the comparisons. What can we make of this?

The simplistic - and likely wrong - interpretation is that legal and refugee immigration result in higher crime rates, but illegal immigration results in lower crime rates. 

But why might this be an incorrect interpretation, especially since almost every comparison was statistically significant? (The only relationship that wasn't significant was between legal immigration and property crime.) Well, just because something is statistically significant doesn't mean that it is meaningful. When an association is statistically significant, it says that there's probably a real world explanation for the relationship, but it doesn't measure the magnitude of the effect, and it's very hard to isolate exactly what is causing that effect. Therefore, it would be irresponsible to conclude that legal immigration or refugee immigration actually increases crime, and that illegal immigration actually decreases crime.

Also, we must be aware that there are a lot of factors - and lurking variables - that could influence crime rates besides immigration. The fact that legal immigration and refugee immigration had positive relationships with crime could be due to broader trends. Perhaps something was going on in the United States that led to both higher crime and higher immigration. For example, maybe a bad economy leads to higher crime, and a bad economy may also lead to the government boosting its immigration numbers to spark economic growth. Similarly, it is possible that the negative relationship between crime and illegal immigration is due some other quirk: perhaps the United States is a more desirable destination for illegal immigrants when crime is low, as they flee more dangerous societies. In this case, the crime causes the immigration, and not the other way around.

It's also important to point out caveats in regards to the illegal immigration numbers we used. First of all, there was annual data from 2005 to 2014 in that data set, but only observations in five year increments prior to 2005. Therefore, it made sense to interpolate using a straight line method. Filling in the gaps -- while sensible -- makes the data less reliable. Also, while the legal immigration and refugee immigration data is exact -- and fastidiously recorded by the government -- the illegal immigration numbers are merely estimates. The shape of how illegal immigrants have entered the country is inexact, as are the raw totals. The fact that undocumented people are difficult to measure is another reason to question those results.

Nevertheless, the fear about illegal immigrants bringing crime seems unfounded. My hypothesis that illegal immigration wouldn't increase crime is supported by the evidence. This is also true for some of the property crime data in association with legal immigration. Conversely, my hypothesis that legal immigration wouldn't affect the violent crime rate, or that refugee immigration wouldn't affect either crime rates, is not a conclusion to be drawn. We cannot accept the null hypothesis that there is no relationship between crime and those immigration types.
