---
title: "A Study of Immigration and Crime"
author: "David Schwarz"
date: "December 7, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


# The four main datasets are 
# USCrime ; legal ; illegal ; refugee

uscrime <- read.csv("USCrime.csv")

legal <- read.csv("legal.csv")

illegal <- read.csv("illegal.csv")

refugee <- read.csv("refugee.csv")

# the following makes it so that we don't have abbreviated numbers showing in the x and y axes.

options(scipen = 999)
```

## Introduction

This project explores the relationship between immigration and crime in the United States. This is an important topic because some politicians link immigrants to crime, but others don't. The responsible thing is to look at the data, analyze it, and then separate fact from fiction before attributing negative traits to people. 

I'll be looking at violent crime and property crime rates in comparison to three things: legal immigration, illegal immigration, and refugee immigration. The years I'll be studying are 1960-2014, 1990-2014, and 1975-2014, respectively. The dates chosen represent the maximum data available in each particular category. 

My hypotheses are that immigration doesn't have a strong, positive correlation to crime rates in any of these categories.
